
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create  # ? ????? None ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath*:data.sql
      mode: always
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@email.com

jwt:
  secret-key:
  access-token-expiration-minutes: 180
  refresh-token-expiration-minutes: 420

toss:
  test:
    secret-api-key: test_sk_P24xLea5zVAPgGnNPdb3QAMYNwW6
    origin-url: https://api.tosspayments.com/v1
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
      auto: false
    s3:
      bucket: culinari-images
